UI tests [WIP]
lex-js/lex-js pull request #12
Opened 2019-03-05 17:52 UTC by 8084

2019-03-05 18:43 UTC, limitedeternity commented
[Unused module](https://github.com/lex-js/lex-js/blob/9bdea2ba6e6af39bd9c42dcd098b5145c6e85da6/test/coders.js#L2)

2019-03-06 10:51 UTC, limitedeternity requested changes

2019-03-06 10:51 UTC, limitedeternity commented on index.js
> +const Server = require("./server/server");
`server.js` внутри `./server/` следует переименовать в `index.js`, чтобы импорт в этой строчке выглядел так: `require("./server")`

2019-03-06 10:51 UTC, limitedeternity commented on index.js
> +const schemaPath = path.join(internalCwd, "server/config-server-schema.json");
`path.join(internalCwd, "server", "config-server-schema.json");`

2019-03-06 10:51 UTC, limitedeternity commented on server/server.js
> +    this.server = api.listen(config.port, () => {
Может `this.instance`?

2019-03-06 13:45 UTC, limitedeternity approved these changes

2019-03-06 13:49 UTC, limitedeternity commented on server/mock.js
> +const Server = require('./');
А вот тут целесообразнее использовать `./index`
Когда импортируешь файл из `.`, лучше указывать непосредственно имя импортируемого файла, а когда из `..` или выше, то `index` можно пропустить, указав только имя папки.

2019-03-06 13:51 UTC, 8084 commented on server/mock.js
> +const Server = require('./');
Почему целесообразнее?

2019-03-06 13:52 UTC, limitedeternity commented on server/index.js
> +      if (anymatch(config.allowed_files, filePath)) {
Тут можно избежать излишней вложенности с учётом `return`.

2019-03-06 13:53 UTC, limitedeternity commented on server/mock.js
> +const Server = require('./');
Чтобы понятнее было.

2019-03-06 13:55 UTC, klntsky commented on server/mock.js
> +const Server = require('./');
> Чтобы понятнее было.

Почему этот же аргумент нельзя применить к `require("./server")` vs. `require("./server/index")` ?
Ведь `./server` - это директория, а не файл, как и в этом случае.

2019-03-06 14:05 UTC, limitedeternity commented on server/mock.js
> +const Server = require('./');
Проведём аналогию с настройкой сети. 
Ты пробросил порт со своей машины наружу. Твой ресурс доступен извне по адресу 1.2.3.4:80, но "под капотом" запрос идёт к твоей машине в локальной сети - 192.168.1.100:8080.
Для того, чтобы перейти на свой ресурс со своей же машины, ты будешь использовать localhost:8080 или на крайняк - 192.168.1.100:8080, но наименее вероятно будешь смотреть 1.2.3.4:80.
Так же и здесь. Мы импортируем папку `./server` **снаружи**, зная, что "под капотом" нам вернется `./server/index.js`.
Но, находясь внутри папки `server`, импортировать текущую директорию - не очень. Понятно, что результат будет такой же, как если бы ты импортировал `./index`, но импортировать файл в текущей директории вместо текущей директории непосредственно выглядит получше.

2019-03-06 14:16 UTC, limitedeternity requested changes

2019-03-06 14:16 UTC, limitedeternity commented on server/mock.js
> +  constructor () {
`constructor(...arguments)`, иначе `super()` будет нечего передать.

2019-03-06 15:19 UTC, 8084 commented on server/mock.js
> +  constructor () {
Sorry, что?
В `arguments` не только перечисленные параметры, если что.

```
> (function () { console.log(arguments); })(1,2,3)
[Arguments] { '0': 1, '1': 2, '2': 3 }
```

2019-03-06 16:15 UTC, limitedeternity commented on server/mock.js
> +  constructor () {
Сорян, йобу дал

2019-03-06 16:17 UTC, limitedeternity approved these changes

2019-03-12 19:26 UTC, limitedeternity approved these changes

2019-03-21 06:55 UTC, merged