Rewrite
lex-js/lex-js pull request #5
Opened 2019-03-01 16:53 UTC by 8084

2019-03-02 09:42 UTC, limitedeternity commented on .babelrc
> +  "plugins": ["@babel/plugin-transform-runtime"],
Он зачем-то нужен?

2019-03-02 09:42 UTC, limitedeternity commented on index.html
> +    <script type="text/javascript" src="public/js/bundle.min.js"></script>
Относительный путь плох тем, что стоит уйти с главной страницы и до ресурса уже будет не достучаться. Так, если ты на /, то будет возвращаться файл /public/js/bundle.min.js, но если ты заходишь на /about, то браузер попытается достать /about/public/js/bundle.min.js и, разумеется, получит 404. Поддержку запуска по двойному клику нужно отбросить - слишком много подводных.

2019-03-02 09:42 UTC, limitedeternity commented on package.json
> +    "@babel/plugin-transform-runtime": "^7.3.4",
transform-runtime жирнющий. Подумой.

2019-03-02 09:42 UTC, limitedeternity commented on public/css/icons.css
> +  background-image: url("../icons/24/list-ol.png");
Иконки лежат в /public. Такой адрес запросит /icons.

2019-03-02 09:42 UTC, limitedeternity commented on src/coders.js
> +const { charToByteCP866, byteToCharCP866 } = require('./cp866.js');
В /lib до сих пор лежит пустой cp866.js

2019-03-02 10:18 UTC, 8084 commented on index.html
> +    <script type="text/javascript" src="public/js/bundle.min.js"></script>
@limitedeternity 
1. у нас SPA
2. относительный путь хорош тем, что приложение работает (с ограниченной функциональностью) даже если просто открыть index.html в браузере.

> Поддержку запуска по двойному клику нужно отбросить - слишком много подводных.

А именно?

2019-03-02 10:21 UTC, 8084 commented on package.json
> +    "@babel/plugin-transform-runtime": "^7.3.4",
Есть альтернативы?

2019-03-02 10:22 UTC, 8084 commented on public/css/icons.css
> +  background-image: url("../icons/24/list-ol.png");
Адрес резолвится относительно css-файла. Файл в /public/css

2019-03-02 10:22 UTC, 8084 commented on src/coders.js
> +const { charToByteCP866, byteToCharCP866 } = require('./cp866.js');
снесу

2019-03-02 10:27 UTC, 8084 commented on .babelrc
> +  "plugins": ["@babel/plugin-transform-runtime"],
Для async/await (`regeneratorRuntime is not defined` же).

2019-03-02 11:11 UTC, limitedeternity commented on .babelrc
> +  "plugins": ["@babel/plugin-transform-runtime"],
Используй чистые промисы, не нужно тянуть целую артиллерию, чтобы заменить async/await генераторами.

2019-03-02 11:13 UTC, limitedeternity commented on index.html
> +    <script type="text/javascript" src="public/js/bundle.min.js"></script>
1) Листинг не работает
2) Нет возможности сделать path rewrite
3) Все изощрения с путями приведут к тому, что будет сложно усидеть на двух стульях, вместо разработки будем думать над тем, как расположить ресурсы так, чтобы работало и там, и там.

2019-03-02 11:14 UTC, limitedeternity commented on package.json
> +    "@babel/plugin-transform-runtime": "^7.3.4",
Использовать промисы в чистом виде. Либо не транспилировать async/await.

2019-03-02 11:23 UTC, limitedeternity commented on package.json
> +    "bundle:dev": "px --map-inline src/init.js public/js/bundle.min.js",
Что такое px?

2019-03-02 11:27 UTC, limitedeternity commented on package.json
> +    "bundle:dev": "px --map-inline src/init.js public/js/bundle.min.js",
> cargo install pax

Сурьезно?

2019-03-02 11:33 UTC, limitedeternity commented
![2019-03-02 14 32 29](https://user-images.githubusercontent.com/24318966/53681266-11d15c00-3cf8-11e9-9e66-a4d828af535d.png)

2019-03-02 11:54 UTC, limitedeternity commented
Также, вероятно, `README.md` нужно обновить.

2019-03-02 12:09 UTC, 8084 commented on package.json
> +    "@babel/plugin-transform-runtime": "^7.3.4",
Первое накладно, потому что потребует как минимум ещё одно переписывание.

Второе не получится.
Это должно работать в браузерах, которые работают на winxp, и, соответственно, не обновлялись несколько лет. Это не моё требование, если что (надо было раньше сказать, наверное).

2019-03-02 12:14 UTC, 8084 commented
> При загрузке мобильного лейаута случается следующее:

Это баг fastclick, который пока не важен.

> И в мобильном лейауте есть один неприятный баг: когда жмешь на кнопку "меню", сразу же открывается листинг директории. Приходится нажимать кнопку "закрыть", чтобы перейти в меню.

Это не баг. Я специально это добавил задолго до переписывания. Это нужно потому, что на мобильных практически никто не пользуется списком локальных файлов, а листинг вызывается гораздо чаще. И ЕМНИП это должно срабатывать только если локальных файлов нет.

2019-03-02 12:25 UTC, 8084 commented
> При загрузке мобильного лейаута случается следующее:
Ты через devTools делал эмуляцию мобильного интерфейса?
По-моему это потому, что fastclick в этом случае ошибается в определении типа устройства.

2019-03-02 16:44 UTC, limitedeternity commented
> Это нужно потому, что на мобильных практически никто не пользуется списком локальных файлов.

Я пользуюсь переходом к строке по её номеру.

2019-03-02 17:11 UTC, limitedeternity commented
See #6

2019-03-02 21:01 UTC, 8084 commented
> Я пользуюсь переходом к строке по её номеру.

ОК. Думаю, мы можем просто сместить листинг файлов вниз, чтобы он не перекрывал кнопки.

#2

2019-03-02 21:02 UTC, 8084 commented
> Также, вероятно, README.md нужно обновить.

В другом бранче, please.

2019-03-03 12:45 UTC, limitedeternity commented on package.json
> +    "@babel/plugin-transform-runtime": "^7.3.4",
> потому что потребует как минимум ещё одно переписывание

ЕМНИП, не потребуется. Babel просто надо по-человечески настроить.

2019-03-03 21:25 UTC, limitedeternity requested changes

2019-03-03 21:25 UTC, limitedeternity commented on src/content-browser.js
> +    return response.json();
```js
const json = await response.json();
return json;
```

2019-03-03 21:30 UTC, 8084 commented on src/content-browser.js
> +    return response.json();
Это одно и то же, и даже await здесь не обязателен.

Зачем вводить переменную, которую используешь один раз?

2019-03-04 06:24 UTC, limitedeternity commented on src/content-browser.js
> +    return response.json();
Нет, это не одно и то же. Метод json() у response возвращает Promise<Object>.
Нам нужен чисто объект, а не промис, поэтому нужно подождать, когда он резолвнется.

2019-03-04 16:41 UTC, limitedeternity commented
Может, сконвертировать @lex-js в организацию?

2019-03-04 17:29 UTC, 8084 commented on src/content-browser.js
> +    return response.json();
Вложенные друг в друга промисы - это то же самое, что и один промис.

Читаем https://javascript.info/promise-chaining#returning-promises

```
Normally, a value returned by a .then handler is immediately passed to the next handler. But there’s an exception.

If the returned value is a promise, then the further execution is suspended until it settles. After that, the result of that promise is given to the next .then handler.
```

### лирическое отступление

Вообще `Promise` ведёт себя как монада, когда функция, поданная в `.then` возвращает `Promise`.

И все законы монад соблюдаются в этом случае.

https://wiki.haskell.org/Monad_laws

Если на псевдоязыке, `response.json() >>= \json -> return json` - это то же, что `response.json() >>= return` (по правилу eta conversion).

А второй закон монад (right identity) говорит о том, что `m >>= return ≡ m`

Очень советую думать о `Promise` как о монаде, кстати - в случае, когда ситуация становится сложной, помогает.

2019-03-04 18:06 UTC, limitedeternity commented on src/content-browser.js
> +    return response.json();
Ух, жесть.
Проверил - всё так.

2019-03-04 18:06 UTC, limitedeternity approved these changes

2019-03-05 15:28 UTC, merged